name: py312aiwatermark
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - tqdm
  - loguru
  - click
  - pillow
  - opencv
  - pip:
      - --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu126
      - huggingface-hub==0.22.2
      - diffusers>=0.27.0
      - iopaint==1.3.1